#!/usr/bin/env bash
set -euo pipefail

commit_msg_file=${1:?commit message file required}

tmp_file=$(mktemp)
trap 'rm -f "$tmp_file"' EXIT

grep -v -E '^(Co-Authored-By: (Claude|Claude Opus|Anthropic)|Generated by Claude|.*Anthropic attribution).*$' "$commit_msg_file" > "$tmp_file" || true
cp "$tmp_file" "$commit_msg_file"
